name: Tag repo
on:
  push:
    tags:
      - "*"

jobs:
  tag-scan-and-push-final-image:
    name: "Build, scan, and publish tagged image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "owner: ${{ github.repository_owner }} VERSION:${GITHUB_REF#refs/tags/}"
      #- uses: Azure/container-scan@v0
      #  with:
      #    image-name: docker.io/${{ github.repository_owner }}/ghactions:${GITHUB_REF#refs/tags/}
